### ISSUE TITLE
This repository is not the SDK, consider renaming it

### ISSUE THREAD

**Issue by sagrawal31** [Ziggeo/android-sdk-demo#27]
It's mentioned here https://ziggeo.com/docs/sdks/mobile/android that Ziggeo's Android Java SDK is managed publicly on this repo:

![image](https://user-images.githubusercontent.com/1804514/75603097-4a656a80-5af1-11ea-82e6-63507e9b2036.png)

But this repository isn't the actual **Android SDK**. The actual SDK is hosted on jitpack.io at https://jitpack.io/#ZiggeoJitpackService/Android-SDK (which is also damn confusing).

For beginners (or whoever starting to use Ziggeo), it is very confusing and time taking to understand that this repo is not the SDK repo (so do not look for the changelog, commits) instead this is a sample Android app to demonstrate the SDK.

**Consider renaming it to something like `android-sdk-demo`**.

**Comment by 3akat** [comment]
Thanks for suggestions, @sagrawal31. Your arguments make sense, we will consider it with a team.

**Comment by 3akat** [comment]
Renamed.

**Comment by sagrawal31** [comment]
Thank you @3akat
