### ISSUE TITLE
SDK 31 Upgrade

### ISSUE THREAD

**Issue by objectorientedperson** [Ziggeo/android-sdk-demo#34]
Hello,

Recently we needed to upgrade the project's  target SDK number to 31. When we did so, we saw that FullscreenRecorderActivity doesn't have 'exported=true' attribute declared in the manifest. To be able to run the app, we needed ziggeo to upgrade it's activities (that have intent-filter) to have 'exported=true'. (Saw in merged manifest, that FullscreenRecorderActivity and UriParserActivity don't have it.)

Can you please add this? Thanks a lot in advance.

**Comment by 3akat** [comment]
@objectorientedperson please, take a look at the v`2.4.1`

**Comment by objectorientedperson** [comment]
@3akat fixed in v2.4.1. Thank you.
